### ISSUE TITLE
Can you add the option to install the font on github?

### ISSUE THREAD

**Issue by qujihan** [typst-community/setup-typst#14]

**Comment by yusancky** [comment]
This is a good suggestion, as this feature is useful and it's a fact that there are users who have installed fonts on the Runner specifically for Typst. I think it's possible to support a new parameter indicating the fonts to be installed, which can be either a string or a list, with the default being an empty string indicating that no fonts will be installed.

I've had a look under the `font` topic on GitHub: for code, it might be good to support [https://github.com/tonsky/FiraCode](Fira Code); for CJK, I'm going to support [Source Han Sans](https://github.com/adobe- fonts/source-han-sans), [Source Han Serif](https://github.com/adobe-fonts/source-han-serif) and [LXGW WenKai 霞鹜文楷](https://github.com/lxgw/). LxgwWenKai).

For English and English-like, I'm not sure there's a need to support more fonts; for other languages such as Arabic, I haven't found suitable fonts on GitHub at the moment, maybe I will see it later on Google Fonts.

**Comment by jcbhmr** [comment]
I'm a little unclear as to what "option to install the font on github" means but I assume it means "install additional fonts for use with typst"? If so, then this would be a great thing to split into its own GitHub Action called something like "setup-fonts" or "install-google-fonts" or "fetch-adobe-fonts" or something. 🤷‍♀️ just an idea.

**Comment by jcbhmr** [comment]
@qujihan you may be interested in using https://github.com/tecc/fontpm to install Google Fonts in the github actions runner like this:

```yml
- uses: typst-community/setup-typst@v3
- run: cargo install fontpm
- run: fontpm install fira-mono
- run: typst compile uses-fira-mono.typ
```
