### ISSUE TITLE
Also cache package download dir

### ISSUE THREAD

**Issue by Enter-tainer** [typst-community/setup-typst#15]
https://github.com/typst/packages?tab=readme-ov-file#downloads

packages are downloaded each time when action runs. It might be good if we cache them. This may speed up e2e time and avoid failure due to unstable network issues.

**Comment by jcbhmr** [comment]
actually it wouldnt solve the flaky network issues; its still have to download the cached files from actions/cache servers (which are was s3 buckets iirc).

so the question becomes: which is faster? downloading from s3 with all the overhead of "what run/job is this?" plus auth and such via https://npm.im/@actions/cache OR is it faster to just let typst handle things on its own?

https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221

just wanted to point this out before we go all in on caching when it might be faster/better to just chill and let typst handle the caching lol
